RedHatInsights/approval-api

- app/controllers/admins_controller.rb
- app/controllers/mixins/approver_operations_mixin.rb
- app/controllers/mixins/user_operations_mixin.rb
Use params.require to ensure the parameter exists, otherwise will raise an **ActionController::ParameterMissing** error.
> Changed to used params.require to get attributes

- app/services/event_service.rb
- spec/services/event_service_spec.rb
Allow to set Kafka topic through `ENV['KAFKA_TOPIC']`
Some refactoring to use constants.
> Refactor event service to use constants and env

- public/doc/swagger-2.yaml
This PR removed duplicate group_id definition from stage.
Related JIRA ticket: https://projects.engineering.redhat.com/secure/RapidBoard.jspa?rapidView=2404&projectKey=SSP&view=detail&selectedIssue=SSP-113
> Removed duplicate group_id in stage definition in swagger yaml

- config/routes.rb
- spec/swagger_spec.rb
Similar change to what was done in the service-portal-api https://github.com/ManageIQ/service_portal-api/pull/65
For example:
APP_NAME = approval
PATH_PREFIX = ""
Requests Path = /api/v0.0/requests
APP_NAME = approval
PATH_PREFIX = foo/bar
Requests Path = /foo/bar/approval/v0.0/requests
> Make use of APP_NAME and PATH_PREFIX environment variables

- .gitignore
- Gemfile
- config/application.rb
This gives us access to the container logger which
formats output so that is will be properly displayed
in the kibana dashboard and also prints to STDOUT rather
than a file
> Use the manageiq-loggers gem for rails logging

- Gemfile
- config/application.rb
This also requires us to upgrade to rails 5.2.2 in order to bundle with the manageiq-api-common gem.
@bzwei @gmcculloug please review
> Use manageiq-api-common for logging and metrics

- Dockerfile
We need git to use git-based gems, not having this was making
the build fail
@gmcculloug please review
> Install git rpm

- app/services/action_create_service.rb
- app/services/request_create_service.rb
- config/initializers/load_extensions.rb
- lib/exceptions.rb
- spec/services/action_create_service_spec.rb
Allowed state transition through action:
pending -> notify -> notified
notified -> approve/deny -> finished
pending -> skip -> skipped
memo action is always allowed.
Raise an error if not one of above cases.
> Validate whether an action is allowed at current statge state

- app/models/template.rb
- app/models/workflow.rb
- app/services/action_create_service.rb
- app/services/request_create_service.rb
- app/services/stage_update_service.rb
- db/migrate/20190118184631_add_process_setting_to_templates.rb
- db/schema.rb
- spec/requests/requests_spec.rb
- spec/services/action_create_service_spec.rb
- spec/services/request_create_service_spec.rb
- spec/services/stage_update_service_spec.rb
Add columns to store configuration how to connect to a business process engine such as BPM. If no such engine is configured, approval service will automatically move to next stage so that the approvers can still work on a request.
> Automatically move to next stage if no external process is configured

- public/approval/v0.1.0/openapi.json
This PR fixed two issues:
1. Removed duplicated operationId: 
https://projects.engineering.redhat.com/browse/SSP-201
2. Added SUCCESS response for workflow's DELETE/PATCH actions: 
https://projects.engineering.redhat.com/browse/SSP-212
> Renamed operationId to avoid duplicates

- db/migrate/20190315153513_add_process_ref_to_requests.rb
We need this column to store process_instance_id from BPM per request.
> Add process_ref to requests table

- Gemfile
- app/models/workflow.rb
- app/services/jbpm_process_service.rb
- app/services/request_create_service.rb
- app/services/stage_update_service.rb
- config/initializers/load_extensions.rb
- lib/exceptions.rb
- lib/kie/service.rb
- spec/services/action_create_service_spec.rb
- spec/services/jbpm_process_service_spec.rb
- spec/services/request_create_service_spec.rb
- spec/services/stage_update_service_spec.rb
When the `process_setting` and `signal_setting` are configured for a template to connect to an external jbpm kieserver, the code now creates a new process instance when a request is created, and signals the instance when a stage is completed.
> Start or signal a business process through kie_client

- app/models/request.rb
- db/migrate/20190402165411_add_context_to_request.rb
- db/schema.rb
- spec/requests/v1.0/requests_spec.rb
https://projects.engineering.redhat.com/browse/SSP-263
Adding a `context` column to the Request object so we can track how things move through the system. It just stores the `ManageIQ::API::Common::Request.current` object - which is a hash that contains "headers" and "original_url".
> Add context column to Request model

- app/controllers/api/v1x0/workflows_controller.rb
- spec/requests/v1.0/workflows_spec.rb
Fixes https://projects.engineering.redhat.com/browse/SSP-266
It is a typo. Previously we were accepting `group_ids` now it got renamed to `group_refs`.
> Fix permitted group_refs parameter for worflow creation

- config/routes.rb
- spec/requests/v1.0/root_spec.rb
This changes the redirect code from 301 to 302 and fixes an issue
where /openapi.json would redirect to /openapi
Requires https://github.com/ManageIQ/manageiq-api-common/pull/50
@miq-bot assign @Fryguy
> Use the routing helper from api common to handle major version redirects

- app/models/request.rb
- spec/requests/v1.0/requests_spec.rb
https://projects.engineering.redhat.com/browse/SSP-270
Change the way context is stored, so that it only gets set once (when the `Request` is created).
I'll work on changing the MIQ-api-common gem to work with either type of keys as well, that way we don't have to transform the keys in order to use it.
> Change when context is stored on Request

- app/models/encryption.rb
- app/models/template.rb
- app/services/jbpm_process_service.rb
- db/migrate/20190403173445_create_encryptions.rb
- db/schema.rb
- spec/models/encryption_spec.rb
- spec/models/template_spec.rb
- spec/services/jbpm_process_service_spec.rb
1. Create the encryptions table to store encrypted secrets.
2. Config `process_setting` and `signal_setting` of the build-in multi-level approval template to communicate with the internal kieserver through ENV variables.
3. Encrypt passwords
> Seed built-in multi-level approval template to link to internal kieserver

- app/models/template.rb
- spec/models/template_spec.rb
- spec/services/jbpm_process_service_spec.rb
Previously we relied on ENV `KIE_SERVER_HOST` to pass in the kie server host. Now we learned OCP already provided `APPROVAL_PAM_SERVICE_HOST` that we can use. This PR follows the same pattern from https://github.com/ManageIQ/topological_inventory-openshift/blob/master/bin/openshift-operations#L12
> Use ENV set by OCP for kie server host and port

- app/models/template.rb
- spec/models/template_spec.rb
- spec/services/jbpm_process_service_spec.rb
In #84 the BPM parameters are passed in through ENV. From the review comments of the PR to create such ENVs in the OCP deployment it is recommended to have these parameters hardcoded in the app. It makes sense because these parameters are for seeding and should not change.
> Hardcode seeding BPM parameters

- app/controllers/concerns/response.rb
- spec/requests/v1.0/requests_spec.rb
Modify the `OpenApi::Serializer` class to remove `context` from the responses anywhere it is set. This is primarily in the `Request` class for now, but can be expanded in the future if needed
> Remove context column from all responses via OpenApi::Serializer

- docker-assets/run_rails_server
Following logic from https://github.com/ManageIQ/topological_inventory-api/blob/master/docker-assets/run_rails_server
> prepare v2_key at startup

- app/models/request.rb
- app/services/request_create_service.rb
- spec/factories/requests.rb
- spec/models/request_spec.rb
- spec/services/request_create_service_spec.rb
- spec/support/request_spec_helper.rb
When creating a new request in another thread we need to pass the current header/tenant to the thread. This is done through reconstructing from the context attribute in the request model.
Fixes https://github.com/ManageIQ/approval-api/issues/83
> Restore request context in a separate thread

- app/controllers/api/v1x0/requests_controller.rb
- app/models/concerns/filterable.rb
- app/models/request.rb
- public/approval/v1.0/openapi.json
- spec/models/request_spec.rb
This work is to enhance the request API to include attributes `created_at`, `updated_at`, `active_stage` and `total_stages`. The last two attributes are virtual. 
The list query of requests also preloads stages that helps to reduce the number of sql queries.
> Enhance request api to include active stage and timestamps

- public/approval/v1.0/openapi.json
Missing coma in json schema. Need it to generate new JS client.
cc @lgalis 
I think this there is a validator for the openApi schema. Might be nice to turn it on in CI. 
Edit: Some of them are listed here: https://openapi.tools/.
> Fixed missing comma in json schema.

- app/controllers/api/v1x0/stageaction/result.html.erb
- app/controllers/api/v1x0/stageaction/show.html.erb
- app/controllers/api/v1x0/stageaction_controller.rb
Changed to show approver's action inside the status message when approval via open link in the email.
Status message for succeeded action:
Status message for failed action:
> Improved status message in webpage approval

- app/controllers/api/v1x0/mixins/index_mixin.rb
- lib/api/docs.rb
- public/approval/v1.0/openapi.json
- spec/requests/v1.0/workflows_spec.rb
https://projects.engineering.redhat.com/browse/SSP-307
Adds filtering on the index methods via ManageIQ::API::Common::Filter.
> Add index filtering via MIQ Common Gem

- app/models/request.rb
https://projects.engineering.redhat.com/browse/SSP-321
Add a default scope to Request so that it returns the models ordered descending by `created_at`, so it shows the newest ones first.
> Add default_scope to Request model to sort by created_at, descending

- app/controllers/api/v1x0/stageaction/result.html.erb
- app/controllers/api/v1x0/stageaction_controller.rb
In the public link provided in email. if no valid random_access_key is given, or approver is missing in the parameter list, the error page will display meaningless error message.
This PR corrects the error message as:
1. Show `Your request is either expired or has been processed!` if random_access_key is empty or invalid;
2. Show `param is missing or the value is empty: approver` if approver is missing in the params list;
Also removed the empty bracket `action []` if no action is executed.
> Fixed error messages in public web page

- Gemfile
Logging will now include thread local request_id when available.
See https://github.com/ManageIQ/manageiq-loggers/pull/7 (Get the request id from the thread local variable and log it)
> Bump manageiq-loggers version to pick up request_id changes.

- app/models/workflow.rb
- spec/models/workflow_spec.rb
- spec/services/request_create_service_spec.rb
The default workflow that was created from seeding cannot be deleted.
> Prevent default workflow from being destroyed

- app/controllers/api/v1x0/workflows_controller.rb
- app/models/workflow.rb
- spec/controllers/v1.0/workflows_controller_spec.rb
- spec/models/workflow_spec.rb
The backend already prevent the default workflow from being deleted but the API still returns success.
Addressed QE test on https://projects.engineering.redhat.com/browse/SSP-330
> Return 403 when trying to delete default workflow

- public/approval/v1.0/openapi.json
Keeps us in sync with the topology and catalog URLs which have the production and development servers
Topology: ManageIQ/topological_inventory-api#157
Catalog: ManageIQ/catalog-api#213
> Set the URLs based on the topology openapi.json

- app/controllers/api/v1x0/requests_controller.rb
- spec/controllers/v1.0/requests_controller_spec.rb
Addresses the issue that the description field of the request was not saved.
Fixes https://projects.engineering.redhat.com/browse/SSP-454
> Allow to set description of request

- app/models/action.rb
- app/models/concerns/approval_decisions.rb
- app/models/concerns/approval_states.rb
- app/services/action_create_service.rb
- app/services/event_service.rb
- app/services/request_update_service.rb
- app/services/stage_update_service.rb
- spec/services/action_create_service_spec.rb
- spec/services/event_service_spec.rb
- spec/services/request_update_service_spec.rb
- spec/services/stage_update_service_spec.rb
Adding new action type `cancel`.
When cancel action is added to a stage, it cancels the stage and eventually cancels the request.
When a request is canceled, it sends `request_canceled` event to the message bus.
@hsong-rh please add new endpoint `POST /requests/<id>/actions`. We will discuss wither to retire `POST /stages/<id>/actions`
> Backend support of cancel action

- public/approval/v1.0/openapi.json
Add `cancel`, `canceled` in enum list for `action/stage/request`.
> Add missing cancel action in openapi doc

- app/controllers/api/v1x0/requests_controller.rb
- app/controllers/api/v1x0/stageaction_controller.rb
- app/models/concerns/owner_field.rb
- app/models/request.rb
- app/services/request_create_service.rb
- db/migrate/20190612021005_add_owner_to_requests.rb
- db/migrate/20190612021005_rename_requester_to_owner.rb
- db/schema.rb
- public/doc/openapi-3-v1.0.0.json
- spec/controllers/v1.0/actions_controller_spec.rb
- spec/controllers/v1.0/requests_controller_spec.rb
- spec/factories/requests.rb
- spec/models/request_spec.rb
- spec/services/request_create_service_spec.rb
- spec/services/request_update_service_spec.rb
This is the first phase to enable RBAC support in Approval service: renamed attribute `requester` to `owner` in active record `Request`, and populate it with user information whenever request is created.
> Added OwnerField to Request model

- data/rbac_approval_seed.yml
- data/user.yml
- lib/rbac/seed.rb
- lib/tasks/seed_rbac_data.rake
This is the third phase to enable RBAC support in Approval service:
1. `rbac_approval_seed.yml` lists out all needed roles/acls/groups/policies for approval service; 
2. `rbac_approval_seed.yml` is also used to preconfigure RBAC environment (https://github.com/RedHatInsights/insights-rbac/pull/95);
3. provided a rake task to setup local RBAC environments;
> Predefined RBAC roles/acls/policies/groups

- Gemfile
- lib/rbac/access.rb
- lib/rbac/acls.rb
- lib/rbac/permissions.rb
- lib/rbac/roles.rb
- spec/lib/rbac/access_spec.rb
- spec/lib/rbac/acls_spec.rb
- spec/lib/rbac/roles_spec.rb
- spec/support/rbac_shared_contexts.rb
- spec/support/request_spec_helper.rb
This is the second phase to enable RBAC support in Approval service:
1. create `RBAC::Access` to handle access control list (acls) based on predefined permissions and resource definitions;
2. set role (`admin, approver, owner`) according to acls;
> Added RBAC access acls/roles to service

- app/controllers/api/v1x0/workflows_controller.rb
- app/services/access_process_service.rb
- app/services/workflow_create_service.rb
- app/services/workflow_update_service.rb
- lib/rbac/policies.rb
- spec/controllers/v1.0/workflows_controller_spec.rb
- spec/services/access_process_service_spec.rb
- spec/services/workflow_create_service_spec.rb
- spec/services/workflow_update_service_spec.rb
This is the fourth PR to enable RBAC support in Approval service:
Create or update RBAC roles when a workflow with groups information is created or updated.
> Added services to create RBAC roles based on workflow's groups

- app/controllers/api/v1x0/stageaction_controller.rb
- app/controllers/concerns/exception_handler.rb
Changed return code to 400 (bad request) error code when posting an action with invalid content:
https://projects.engineering.redhat.com/browse/SSP-502
> Corrected return code for Action API with invalid content

- app/services/access_process_service.rb
- lib/rbac/roles.rb
Added scope option when initializing RBAC roles for two use cases:
1. use `:scope => 'principal'` when checking the roles for user;
2. use `:scope => 'account'` when creating approval roles for groups if needs;
https://projects.engineering.redhat.com/browse/SSP-776
> Added scope option when listing roles

- app/controllers/api/v1x0/requests_controller.rb
- spec/controllers/v1.0/requests_controller_spec.rb
Both `admin` and `approver` can be a regular requester. Changed to allow them to use endpoint `requester/requests`
> Allow admin/approver to use requester/requests endpoint

- app/controllers/api/v1x0/actions_controller.rb
- public/doc/openapi-3-v1.0.0.json
- spec/controllers/v1.0/actions_controller_spec.rb
1. Corrected spec for endpoints:`stages/{id}` and `/requests/{request_id}/actions`;
2. Added role checking before posting actions:
`admin`:     can create all kinds of actions
`approver`:  can not create 'cancel' action
`requester`: can only create 'cancel' action
> Updated openapi spec and check roles when post actions

- app/controllers/api/v1x0/requests_controller.rb
- config/routes.rb
- public/doc/openapi-3-v1.0.0.json
- spec/controllers/v1.0/requests_controller_spec.rb
https://projects.engineering.redhat.com/browse/SSP-794
Since each login may have multiple personas, we introduced three persona specific endpoints for requests, namely
/admin/requests
/approver/requests
/requester/requests
However this causes problem for GraphQL query because the persona is not a built in attributes of requests. Now we decide to remove these endpoints and take the persona parameter from header. The mapping from old endpoint to new is as follows
/admin/requests -> /requests with header x-rh-persona=approval/admin
/approver/requests -> /requests with header x-rh-persona=approval/approver
/requester/requests -> /requests with header x-rh-persona=approval/requester
A request without header x-rh-persona is the same as approval/requester
A request with unknown x-rh-persona …
> Remove persona specific endpoint and take persona in header

- app/controllers/api/v1x0/actions_controller.rb
- spec/controllers/v1.0/actions_controller_spec.rb
https://projects.engineering.redhat.com/browse/SSP-809
Notify is an action performed by system but under the context of requester. This is a temporary solution to allow regular user to add a `notifiy` action. We will come up a better solution for system to perform all needed actions.
> Temporary allow regular user like BPM to create 'notify' action

- app/models/tag_link.rb
- db/migrate/20191011161512_change_tag_links_index.rb
- db/schema.rb
- spec/models/tag_link_spec.rb
- spec/models/workflow_spec.rb
The uniqueness validation should take tenant_id into consideration. ActsAsTenant does not automatically add the scope to validation.
> Fix tag_link uniqueness validation

- app/services/workflow_link_service.rb
- app/services/workflow_unlink_service.rb
- spec/services/workflow_link_service_spec.rb
Create a separate service class to do the unlinking. It does not delete the entry from `tag_links` table. Instead it should attempt to delete resolved tag name from the resource object (to be followed up by another PR).
> add workflow_unlink_service

- .travis.yml
- Gemfile
- app/models/workflow.rb
- db/migrate/20191014102030_add_sequence_to_workflows.rb
- db/schema.rb
- public/doc/openapi-3-v1.0.0.json
- spec/models/workflow_spec.rb
Backend support to enable workflow sequencing management per tenant using ActsAsList.
When a new workflow is created, the sequence is automatically assigned to the next available value if it is not provided by the caller.
Workflow update API allows the caller to directly update. No dedicated API and service class are needed.
When a workflow sequence is changed, all affected workflows' sequences will be automatically updated.
> Schema and model change to add sequence to workflow

- spec/controllers/v1.0/requests_controller_spec.rb
- spec/models/tag_link_spec.rb
1. Fix a spec waring on `not_to raise_error`
2. Disable a sporadical spec error. An issue was created in https://github.com/ManageIQ/approval-api/issues/196
> Two rspec issues

- app/controllers/api/v1x0/requests_controller.rb
- config/routes.rb
- public/doc/openapi-3-v1.0.0.json
- spec/controllers/v1.0/requests_controller_spec.rb
The focus of this work is on openapi spec for request creation
Remove request creation endpoint `/workflows/<id>/requests`
New creation endpoint `/requests`
The request creation body requires tag information.
Temporarily disable request creation through service class
Temporarily disable resource controller spec
> New request creation endpoint that requires resource tags

- app/models/request.rb
- app/models/request_context.rb
- app/services/request_create_service.rb
- db/migrate/20191018142121_create_request_contexts.rb
- db/schema.rb
- spec/factories/requests.rb
- spec/models/request_spec.rb
Move `content` and `context` into table `request_contexts`.
Share the same `request_context` when a child request is created.
> Move content and context into a separate table and share with children

- app/services/remote_tagging_service.rb
- spec/services/add_remote_tags_spec.rb
The 403 from a direct HTTP call should be converted back to a well known exception Exceptions::NotAuthorizedError so we can forward it to the UI
> Report 403 errors from HTTP Post calls

- app/controllers/api/v1x0/mixins/index_mixin.rb
- app/controllers/api/v1x0/workflows_controller.rb
- config/routes.rb
- public/doc/openapi-3-v1.0.0.json
- spec/controllers/v1.0/workflows_controller_spec.rb
- spec/support/request_spec_helper.rb
Due to the request validation, here we changed:
1. replace ` POST /workflows/resolve` with `GET /workflows?remote_object_query_params` to resolve workflows based on remote object;
2. remove `POST /workflows/unlink` with `DELETE /workflows/unlink`
> Changed resolve/link/unlink into GET/POST actions

- app/controllers/api/v1x0/requests_controller.rb
- public/doc/openapi-3-v1.0.0.json
Edit the request model in openapi spec to reflect the changes brought in by #204 
GET /request/<id>/requests is not implemented. Should be in another PR.
> Amend request model in openapi spec

- Gemfile
- app/controllers/api/v1x0/actions_controller.rb
- app/models/action.rb
- app/models/concerns/approval_states.rb
- app/models/request.rb
- app/services/action_create_service.rb
- app/services/event_service.rb
- app/services/request_create_service.rb
- app/services/request_update_service.rb
- spec/models/request_spec.rb
- spec/services/request_create_service_spec.rb
- spec/services/request_update_service_spec.rb
Rewrite the login to create and execute a request. 
Create sub_requests based on resolved workflows. 
Execute a request through actions.
Update the root request based on its children's states.
Remove acts_as_tree gem since our use of child_parent relation is very simple.
Disable some spec tests - to be added with follow-up PRs.
Depends on #204
> Execute a request through sub_requests

- app/services/request_create_service.rb
- spec/services/request_create_service_spec.rb
Each leaf request's workflow must present for RBAC purpose.
> Set default workflow if leaf request's workflow is not set

- app/services/workflow_find_service.rb
- spec/services/workflow_find_service_spec.rb
The `select` and `distinct` keywords must be placed at the end of the query otherwise we would get error `ArgumentError (Relation passed to #or must be structurally compatible. Incompatible values: [:select, :distinct])`
> Fix select distinct query syntax

- app/controllers/api/v1/mixins/rbac_mixin.rb
- spec/controllers/v1.0/requests_controller_spec.rb
For `owner` role,  current logic will filter out all sub requests by `:parent_id => nil`. Removed the filter to fix the problem.
> Fixed to list child requests

- app/services/request_create_service.rb
As for now we still need to act as an org_admin in order to get a group name from RBAC service.
> Switch context to get group name

- app/services/add_remote_tags.rb
- app/services/delete_remote_tags.rb
- app/services/workflow_link_service.rb
- app/services/workflow_unlink_service.rb
- spec/controllers/v1.0/workflows_controller_spec.rb
- spec/services/add_remote_tags_spec.rb
- spec/services/delete_remote_tags_spec.rb
- spec/services/workflow_find_service_spec.rb
- spec/services/workflow_link_service_spec.rb
In an earlier PR I missed the fact that the class name
was plural but the input parameters were singular. Fixed
input parameters so that its consistent with class name
Missed from PR https://github.com/RedHatInsights/approval-api/pull/235
> Fix the input parameter to match the class names

- app/services/get_remote_tags.rb
- app/services/mixins/tag_mixin.rb
- spec/services/get_remote_tags_spec.rb
Since tagging was re-implemented it has ony one attibute called
:tag, so its difficult to filter based on internal variables for
Tags(:namespace, :name, :value)
> Disable filtering when make GET requests to get tags.

- app/services/action_create_service.rb
- spec/services/action_create_service_spec.rb
Only allow `approve/deny` actions on child requests.
> Limit approve/deny actions only on child requests

- app/models/workflow.rb
- spec/models/workflow_spec.rb
This is a bug. Both method failed for `Always Approve` workflow because it does not have a template.
> Fix Workflow#external_processing? and #external_signal?

- app/controllers/application_controller.rb
- spec/controllers/v1.0/root_controller_spec.rb
https://projects.engineering.redhat.com/browse/SSP-1145
This makes it consistent with topology, sources and catalog
There was an earlier PR https://github.com/RedHatInsights/approval-api/pull/121
which was closed without merging.
> openapi.json can be retrieved without credentials

- docker-assets/run_rails_server
https://projects.engineering.redhat.com/browse/SSP-1150
Following the same thing I did on Catalog, update the CMD script so the container will only start if the datase migrations (and seeding in this case) succeed. 
Related Catalog PR: https://github.com/RedHatInsights/catalog-api/pull/563
> Update CMD script to only start the rails server if the migrations succeed

- app/controllers/api/v1/actions_controller.rb
- app/controllers/api/v1/mixins/rbac_mixin.rb
- public/doc/openapi-3-v1.0.0.json
- spec/controllers/v1.0/actions_controller_spec.rb
Refactor the operation validation based on user's role.
Allow `notify` operation with header `x-rh-random-access-key`. This operation is not documented for public use in openapi spec. It is designed to be used as an internal call from PAM.
> More restrict action operation validation

- Dockerfile
Forgot to add this back in yesterday, reduces image size by 33MB.
@miq-bot add_reviewer @gmcculloug
> Add rm -rvf /root/.bundle/cache/ to Dockerfile to reduce size of image

- app/controllers/status_controller.rb
- config/routes.rb
Following the pattern created in the common gem, catalog PR for reference: https://github.com/RedHatInsights/catalog-api/pull/528/files
This will allow us to add a livenessProbe to the deployment config so the pod will auto restart if something is wrong.
> Add /health for liveness probe

- public/doc/openapi-3-v1.0.0.json
- spec/controllers/v1.0/workflows_controller_spec.rb
Update the open api spec to limit the sequence number to be positive. The parse automatically reinforce it and returns 400 if not conformed.
> Sequence number must be positive

- app/services/request_create_service.rb
- spec/services/request_create_service_spec.rb
We should not leave `Request#group_name` attribute blank if the request is auto approved by system because this attribute is now used by UI to identify each (sub) request.
> Fill System approver to group_name for requests using default workflow

- config/environments/development.rb
- config/environments/production.rb
Laura reached out to me why the CSS wasn't loading from the Rails application, tried just turning on the `public_file_server` but that wasn't enough, so I changed the assets prefix as well. 
This way it generates the links in the UI for the fonts/css correctly.
> Change asset path so fonts/css load correctly

- app/controllers/api/v1/stageaction/show.html.erb
- app/controllers/api/v1/stageaction_controller.rb
- spec/controllers/v1.0/stageaction_controller_spec.rb
This is a follow-up fixes as required in #277 and #283 
Before the fix:
> Fix time/date format and capital letters

- app/models/workflow.rb
- app/services/request_create_service.rb
- db/migrate/20200226115345_delete_always_approve_from_workflows.rb
- db/schema.rb
- spec/controllers/v1.0/graphql_controller_spec.rb
- spec/controllers/v1.0/requests_controller_spec.rb
- spec/controllers/v1.0/workflows_controller_spec.rb
- spec/models/workflow_spec.rb
- spec/services/request_create_service_spec.rb
https://projects.engineering.redhat.com/browse/SSP-856. 
If no workflow is linked to any resource in an order, the default is already always approve. There is no need to ask a user to specifically choose an always approve workflow.
> Remove Always approve workflow

- app/controllers/api/v1/stageaction/_request.html.erb
- app/controllers/api/v1/stageaction_controller.rb
Following changes in https://github.com/RedHatInsights/catalog-api/pull/607,  added `Platform` in email notification.
https://projects.engineering.redhat.com/browse/SSP-1291
> Added Platform in email notification

- app/controllers/api/v1/mixins/rbac_mixin.rb
- spec/controllers/v1.0/requests_controller_spec.rb
https://projects.engineering.redhat.com/browse/SSP-1323
We need to check permission for both approvers and requesters. The permission is granted if either check passes.
> Check permission for both approvers and requesters

- app/controllers/api/v1/mixins/rbac_mixin.rb
- spec/controllers/v1.0/requests_controller_spec.rb
Stable branch PR of https://github.com/RedHatInsights/approval-api/pull/299
https://projects.engineering.redhat.com/browse/SSP-1323
We need to check permission for both approvers and requesters. The permission is granted if either check passes.
> [Stable] Check permission for both approvers and requesters

- app/controllers/api/v1/actions_controller.rb
- app/controllers/api/v1/stageaction_controller.rb
- app/models/random_access_key.rb
- app/models/request.rb
- app/services/jbpm_process_service.rb
- app/services/request_update_service.rb
- db/migrate/20200302143829_create_random_access_keys.rb
- db/schema.rb
- spec/controllers/v1.0/actions_controller_spec.rb
- spec/controllers/v1.0/stageaction_controller_spec.rb
- spec/models/request_spec.rb
- spec/services/jbpm_process_service_spec.rb
- spec/services/request_create_service_spec.rb
Each approver per request has a unique random_access_key
https://projects.engineering.redhat.com/browse/SSP-1313
Before the url looks like https://ci.cloud.redhat.com/api/approval/v1.0/stageaction/ec0150c649d9b5fbfb74439eeaaffc35?approver=Z21jY3VsbG9AcmVkaGF0LmNvbQ==
The new url looks like
https://ci.cloud.redhat.com/api/approval/v1.0/stageaction/ec0150c649d9b5fbfb74439eeaaffc35
> Move random_access_key into a separate table

- app/services/jbpm_process_service.rb
- app/services/request_update_service.rb
- lib/kie/service.rb
- spec/services/jbpm_process_service_spec.rb
Update request's state to `failed` when KIE has errors.
> Update request state when KIE server raises errors

- app/controllers/api/v1.rb
- app/controllers/api/v1/root_controller.rb
- app/controllers/api/v1x0.rb
- app/controllers/api/v1x1.rb
This allows for `/v1/openapi.json` to redirect to the latest minor version `v1.1`
Also fixes an issue where `/v1.1/openapi.json` was returning a 400.
Below are examples of the api requests and their subsequent log entries:
```
curl localhost:3000/api/v1.1/openapi.json
[----] I, [2020-03-18T13:39:21.993990 #91634:3fdb98032e98]  INFO -- : Started GET "/api/v1.1/openapi.json" for ::1 at 2020-03-18 13:39:21 -0400
[----] I, [2020-03-18T13:39:22.058501 #91634:3fdb98032e98]  INFO -- : Processing by Api::V1x1::RootController#openapi as */*
[----] I, [2020-03-18T13:39:22.058770 #91634:3fdb98032e98]  INFO -- : Request started http://localhost:3000/api/v1.1/openapi.json
[----] I, [2020-03-18T13:39:22.068380 #91634:3fdb98032e98]  INFO -- : Request ended http://localhost:3000/api/v1.1/openapi.json …
```
> Allow for major version redirects to work for root_controller

- app/controllers/api/v1x1.rb
Adds the missing v1x0 reference to `GraphQLController` in the `v1x1` version module.
BEFORE: ( on CI )
```
curl -u user:password -X POST https://ci.cloud.redhat.com/api/approval/v1.1/graphql
<!DOCTYPE html>
<html>
<head>
<title>The page you were looking for doesn't exist (404)</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
body {
background-color: #EFEFEF;
color: #2E2F30;
text-align: center;
font-family: arial, sans-serif;
margin: 0;
}
```
AFTER: ( local changes )
```
curl -X POST localhost:3000/api/v1.1/graphql/                                                               
{"errors":[{"status":400,"detail":"OpenAPIParser::NotExistRequiredKey: #/components/schemas/GraphqlIn missing required parameters: query"}]}
```
JIRA: …
> Add the correct inherited graphql version into the v1.1 version module

- app/controllers/api/v1x0/mixins/rbac_mixin.rb
- app/controllers/api/v1x0/requests_controller.rb
- spec/controllers/v1.0/actions_controller_spec.rb
- spec/controllers/v1.0/requests_controller_spec.rb
https://projects.engineering.redhat.com/browse/SSP-1370
Before for endpoint `/requests` the controller always limits the collection to parent requests where `:parent_id => nil` and continues to narrow the collection according to persona. However approvers can see never see parent requests but only qualified children.
With this fix the endpoint now includes child requests that approvers can see.
Also we discover that `access_control_entries` are no longer needed because each child request has `group_ref` attribute to filter approvers and `owner` attribute to filter requesters. 
A follow-up PR will completely remove `access_control_entries` table.
> API /requests lists child requests visible to approver

- Gemfile
- app/controllers/api/v1x0/mixins/rbac_mixin.rb
- app/models/group.rb
- app/models/user.rb
- app/services/context_service.rb
- spec/controllers/v1.0/actions_controller_spec.rb
- spec/controllers/v1.0/requests_controller_spec.rb
- spec/models/group_spec.rb
- spec/models/user_spec.rb
- spec/services/context_service_spec.rb
Refactor `ContentService#act_as_org_admin` method wherever we need to call RBAC with org_admin right to use the newly supported service_to_service call feature from RBAC team.
Wait for a new `insights-api-common` gem release that include https://github.com/RedHatInsights/insights-api-common-rails/pull/168.
> Use service to service call to RBAC service where required

- app/controllers/api/v1x0/actions_controller.rb
- app/controllers/api/v1x0/requests_controller.rb
- app/models/request.rb
- app/policies/action_policy.rb
- app/policies/mixins/rbac_mixin.rb
- app/policies/request_policy.rb
- spec/controllers/v1.0/actions_controller_spec.rb
- spec/policies/action_policy_scope_spec.rb
- spec/policies/action_policy_spec.rb
- spec/policies/request_policy_scope_spec.rb
- spec/policies/request_policy_spec.rb
- spec/support/rbac_shared_contexts.rb
The main purpose is to remove the need of get id list of approver or requester visible resources. All queries are direct. As a result the super long query string with all IDs should not appear in the log.
Prove the requester is now able to see actions. Fixed spec for this query.
> Query performance optimization

- app/controllers/api/v1x0/graphql_controller.rb
In GraphQL controller we now pass a scope rather than the model class itself, so that the `parent_id` will be not force to set to `nil` in https://github.com/RedHatInsights/approval-api/blob/stable/app/policies/request_policy.rb#L14
> Fix to allow graphql to fetch child requests

- app/controllers/api/v1x0/mixins/index_mixin.rb
- app/controllers/api/v1x0/workflows_controller.rb
- public/doc/openapi-3-v1.2.json
- spec/controllers/v1.0/workflows_controller_spec.rb
Same as I did for catalog here: https://github.com/RedHatInsights/catalog-api/pull/647
This allows the user to add `?sort_by=field` to sort the index by any field. 
cc @gmcculloug @bzwei
> Add `sort_by` option from common gem to index operations

- app/controllers/api/v1x0/actions_controller.rb
- app/controllers/api/v1x0/graphql_controller.rb
- app/controllers/api/v1x0/requests_controller.rb
- app/controllers/application_controller.rb
- app/models/action.rb
- app/models/application_record.rb
- app/models/concerns/metadata.rb
- app/models/request.rb
- app/models/template.rb
- app/models/workflow.rb
- app/policies/action_policy.rb
- app/policies/application_policy.rb
- app/policies/mixins/rbac_mixin.rb
- app/policies/request_policy.rb
- app/policies/template_policy.rb
- app/policies/user_context.rb
- app/policies/workflow_policy.rb
- public/doc/openapi-3-v1.2.json
- spec/controllers/v1.0/graphql_controller_spec.rb
- spec/controllers/v1.0/requests_controller_spec.rb
- spec/controllers/v1.0/templates_controller_spec.rb
- spec/controllers/v1.0/workflows_controller_spec.rb
- spec/policies/action_policy_scope_spec.rb
- spec/policies/action_policy_spec.rb
- spec/policies/request_policy_scope_spec.rb
- spec/policies/request_policy_spec.rb
- spec/policies/template_policy_spec.rb
- spec/policies/workflow_policy_spec.rb
Added user capabilities feature in Approval. The user_capabilities in metadata will have following keys. Values can be either true or false:
1. Template: `"metadata"=>{"user_capabilities"=>{"show"=>true}}`
2. Workflow: `"metadata"=>{"user_capabilities"=>{"update"=>true, "destroy"=>true, "link"=>true, "unlink"=>true, "create"=>true, "show"=>true}}`
3. Request:  `"metadata"=>{"user_capabilities"=>{"approve"=>true, "cancel"=>true, "create"=>true, "deny"=>true, "memo"=>true, "show"=>true}}`
Also having refactoring, moved `authorize` check logic in `index` to corresponding `policy scope`.
> Enabled user capabilities in Approval

- app/services/request_create_service.rb
- spec/services/request_create_service_spec.rb
Fix a bug brought in by #310. Before `group_ref` is group's uuid. Now we need to get by `group_ref['uuid']`.
Spec test did not catch the bug because we use rspec's `double` to mock rbac calls. It does not check whether the argument has correct type.
Since we do a group validate at the beginning, we do not need to get the group name from rbac. Instead we can directly use `group_ref['name']`
> Fix getting uuid from group_ref

- Gemfile
Fixes failing tests with api-common 3.10
> Lock api-common to 3.9

- app/controllers/api/v1x0/graphql_controller.rb
- app/models/request.rb
- app/policies/action_policy.rb
- app/policies/application_policy.rb
- app/policies/request_policy.rb
- app/policies/template_policy.rb
- app/policies/user_context.rb
- app/policies/workflow_policy.rb
- app/services/request_create_service.rb
- app/services/request_update_service.rb
- spec/controllers/v1.0/graphql_controller_spec.rb
- spec/models/request_spec.rb
- spec/policies/action_policy_scope_spec.rb
- spec/policies/request_policy_scope_spec.rb
- spec/policies/template_policy_scope_spec.rb
- spec/policies/workflow_policy_scope_spec.rb
- spec/services/request_create_service_spec.rb
- spec/support/rbac_shared_contexts.rb
https://projects.engineering.redhat.com/browse/SSP-1445
This PR will process graphQL query whose params contain `id`.
> Used GraphQL params to narrow policy scopes

- app/models/workflow.rb
- spec/models/workflow_spec.rb
Before we came up with a customized `unique_with_same_tenant` method to handle a special case for `Always Approve` workflow. Since this workflow has been removed, we can switch to use standard rails' validation for uniqueness.
> Use rails validates for name

- app/models/group.rb
- app/services/mixins/group_validate_mixin.rb
- spec/controllers/v1.0/requests_controller_spec.rb
- spec/controllers/v1.0/workflows_controller_spec.rb
- spec/models/group_spec.rb
- spec/services/request_create_service_spec.rb
- spec/services/request_update_service_spec.rb
- spec/services/workflow_create_service_spec.rb
- spec/services/workflow_find_service_spec.rb
- spec/services/workflow_get_service_spec.rb
- spec/services/workflow_link_service_spec.rb
- spec/services/workflow_update_service_spec.rb
Allow admin groups to be added to approval process
https://projects.engineering.redhat.com/browse/SSP-1435
> Extend approver group validation to admin group

- app/controllers/api/v1x0/workflows_controller.rb
This `rescue` is for always approve workflow, which has been removed.
> Remove unused  rescue

- .gitattributes
The [library that Github](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-repository-languages) uses to detect a repo language is detect this repo as being mostly CSS, when in reality it would be more accurate to display as a Ruby repo.
This `.gitattributes` file will cause the library to ignore CSS files and should promote the repo and mainly a ruby based repo.
> Add Github .gitattributes file

- app/models/workflow.rb
- spec/models/workflow_spec.rb
We should not adjust sequences if current value does not change. Otherwise each save causes the numbers moving higher.
https://projects.engineering.redhat.com/browse/SSP-1536
The above ticket reported the problem occurs at GET. It is because each get does validation on  groups and save with updated group names.
It also resolves a warning on deprecated call.
> Adjust sequences only when current value changes

- Gemfile
- app/models/workflow.rb
- lib/tasks/sync_rbac_roles.rake
- spec/models/workflow_spec.rb
- spec/spec_helper.rb
Stable branch PR of https://github.com/RedHatInsights/approval-api/pull/353
Also includes PR https://github.com/RedHatInsights/approval-api/pull/351 `Switched to use the insights-rbac-api-client gem`
> We should not adjust sequences if current value does not change. Otherwise each save causes the numbers moving higher.
> 
> https://projects.engineering.redhat.com/browse/SSP-1536
> 
> The above ticket reported the problem occurs at GET. It is because each get does validation on groups and save with updated group names.
> 
> It also resolves a warning on deprecated call.
> [Stable] Adjust sequences only when current value changes

- app/models/workflow.rb
- spec/models/workflow_spec.rb
- spec/support/tag_resources_shared_context.rb
A followup of #353 and #349 
Optimize the algorithm to avoid gaps when update the sequence.
User provided sequence may not be honored. It will be adjusted to the smallest available sequence if desired number is too large.
> Avoid gaps when adjust sequences

- app/controllers/api/v1x2/stageaction/_request.html.erb
In email, after click `Process request` button, 
before
after:
This PR is related with https://github.com/RedHatInsights/approval-process/pull/51 and https://github.com/RedHatInsights/approval-process/pull/53
> Updated order details information to match with new email template

- Gemfile
Noticed we were lagging behind the other services with the puma version. This version also addresses recent vulnerabilities.
Also dropped version from test gems factory_bot_rails and rspec-rails.
Matching
https://github.com/RedHatInsights/topological_inventory-api/blob/master/Gemfile#L16
https://github.com/RedHatInsights/catalog-api/pull/758
> Bump puma to v4.3

- app/controllers/api/v1x2/workflows_controller.rb
- app/models/workflow.rb
- app/services/workflow_delete_service.rb
- app/services/workflow_update_service.rb
- config/initializers/custom_exception_mappings.rb
- lib/exceptions.rb
- spec/services/workflow_delete_service_spec.rb
Validate sequence to be all positive after save or destroy. Introduce `WorkflowDeleteService` class.
https://projects.engineering.redhat.com/browse/SSP-1567
It as been reported that the workflow sequence sometimes can become negative. It can be reproduced by simultaneously deleting multiple workflows.
Before updating or destroying a workflow, we adjust sequences for other workflows and leave the current workflow's sequence number to be negative and allow it to be updated or destroyed through the AR's built-in process. But in a concurrent situation we may identify the wrong sequence number and leave a negative sequence un-updated.
The solution is to add validation in the `after_save` or `after_destroy` callbacks to ensure no negative sequence number is ever allowed. Transaction rolls back …
> Prevent workflow sequence from becoming negative

- app/services/workflow_create_service.rb
- app/services/workflow_delete_service.rb
- app/services/workflow_update_service.rb
- config/initializers/custom_exception_mappings.rb
- spec/config/initializers/custom_exception_mappings_spec.rb
- spec/controllers/v1.2/workflows_controller_spec.rb
We renamed an error class name in #367 that needs to be changed in the error conversion list.
> Fix mis-spelled error class name

- app/controllers/api/v1x2/workflows_controller.rb
- app/models/workflow.rb
- app/services/workflow_create_service.rb
- app/services/workflow_delete_service.rb
- app/services/workflow_update_service.rb
- config/initializers/custom_exception_mappings.rb
- lib/exceptions.rb
- spec/config/initializers/custom_exception_mappings_spec.rb
- spec/controllers/v1.2/workflows_controller_spec.rb
- spec/services/workflow_delete_service_spec.rb
cherry-pick changes from #367 and #372
>Validate sequence to be all positive after save or destroy. Introduce WorkflowDeleteService class.
>
>https://projects.engineering.redhat.com/browse/SSP-1567
>
>It as been reported that the workflow sequence sometimes can become negative. It can be reproduced by simultaneously deleting multiple workflows.
>
>Before updating or destroying a workflow, we adjust sequences for other workflows and leave the current workflow's sequence number to be negative and allow it to be updated or destroyed through the AR's built-in process. But in a concurrent situation we may identify the wrong sequence number and leave a negative sequence un-updated.
>
>The solution is to add validation in the after_save or after_destroy callbacks to ensure no negative sequence …
> [Stable] Prevent workflow sequence from becoming negative

- app/services/remote_tagging_service.rb
- config/initializers/custom_exception_mappings.rb
- lib/exceptions.rb
- lib/kie/service.rb
- spec/lib/kie/service_spec.rb
- spec/services/add_remote_tags_spec.rb
- spec/services/delete_remote_tags_spec.rb
- spec/services/get_remote_tags_spec.rb
- spec/support/tag_resources_shared_context.rb
https://projects.engineering.redhat.com/browse/SSP-1301
In this PR:
1. Separated `NetworkError` and `TimedOutError` from common `KieError` for PAM service;
2. Separated `NetworkError`, `TimedOutError` and `NotAuthorizedError` from `Faraday` exceptions, marked other errors as `TaggingError`, for remote tagging services
> Separate errors of external services into more detailed categories

- app/models/workflow.rb
- app/services/workflow_create_service.rb
- app/services/workflow_delete_service.rb
- app/services/workflow_update_service.rb
- config/initializers/custom_exception_mappings.rb
- spec/controllers/v1.2/workflows_controller_spec.rb
Also changes to order-by-id to reduce the possibility of deadlocking.
The problem was reported in QA env, not reproducible by any spec unit tests. Add rescue for deadlocked error in all workflow services that may modify sequence.
https://projects.engineering.redhat.com/browse/SSP-1592
> Rescue Active::DeadLocked error and retry

- app/models/workflow.rb
- public/doc/openapi-3-v1.2.json
- spec/controllers/v1.2/workflows_controller_spec.rb
This PR adds another attribute `object_dependencies` into the metadata of `workflow`. It stores the dependent categories, which is used by UI to post warning message before workflow is deleted.
New format of metadata looks like: 
```yaml
{
"user_capabilities"=>{
"create"=>true,
"unlink"=>true,
"show"=>true,
"update"=>true,
"destroy"=>true,
"link"=>true
},
"object_dependencies"=>{
"catalog"=>[
"Portfolio",
"PortfolioItem"
],
"sources"=>[
"Source"
]
}
}
```
where `catalog`, `sources` are the `app` names, the array value contains the dependent categories.
> Add object_dependencies into workflow metadata

- app/models/workflow.rb
- app/policies/workflow_policy.rb
- app/services/event_service.rb
- spec/models/workflow_spec.rb
- spec/policies/workflow_policy_spec.rb
- spec/services/event_service_spec.rb
In this PR, workflow is forbid to delete if one of its associated requests is still running: (state is `pending`, `started` or `notified`). Try to delete such a workflow will raise an error. 
Workflow will allow to be deleted If all its associated requests are completed. After workflow is deleted, the foreign key `workflow_id` of these completed requests will set to `nil`.
Whenever the workflow is deleted, the associated `TagLinks` will always be removed too. 
https://projects.engineering.redhat.com/browse/SSP-1544
> Add checking on state of requests before deleting approval process

- .travis_scripts/openapi-validator.sh
Sometimes script openapi-generator-cli.sh fails to fetch openapi-generator's latest version. We then fall back to use current latest 4.3.1.
> Fall back to use default version for openapi-generator-cli validation

- app/models/workflow.rb
- spec/models/workflow_spec.rb
This is a comer case. Do not adjust neighboring sequences when attempt to move the last sequence higher.
https://projects.engineering.redhat.com/browse/SSP-1650
> Handle a special case when moving last sequence higher

- app/models/workflow.rb
- app/services/workflow_delete_service.rb
- spec/models/workflow_spec.rb
- spec/services/workflow_delete_service_spec.rb
Fix the bug that we send workflow_deleted event after every commit since it is only needed for destroy operation.
It is more appropriate to send the event in the service class rather than in the model class
> Send workflow deleted event in service class

- app/controllers/api/v1x2/workflows_controller.rb
- app/models/workflow.rb
- app/policies/workflow_policy.rb
- app/services/sequence_update_service.rb
- config/routes/v1x2.rb
- db/migrate/20200226115345_delete_always_approve_from_workflows.rb
- db/migrate/20200630145352_add_internal_sequences_to_workflow.rb
- db/schema.rb
- public/doc/openapi-3-v1.2.json
- spec/controllers/v1.2/workflows_controller_spec.rb
- spec/models/workflow_spec.rb
- spec/policies/workflow_policy_spec.rb
Introduce internal_sequence column to workflows table. The column type is numeric type that supports float points with higher precision. The goal is to update only one sequence number while keeping other sequences unchanged and still reach the new desired sorting by sequence.
With this commit we still maintain both internal_sequence and the existing sequence columns and the both sorting are kept synchronized. We will eventually retire old sequence column after UI switches to use internal_sequence.
/workflows/:id/sequence endpoint is added to allow to modify current sequence with an increment. It can be also literally `top` or `bottom`.
> Add internal_sequence to workflow

- app/services/jbpm_process_service.rb
- spec/services/jbpm_process_service_spec.rb
Previously we only rescue KieError when connect to jbpm service and mark the request failed. This does not catch other exception such as NetworkError.
With this fix we now rescue all errors and fail the request.
> Rescue all errors when connect to jbpm service

- .dockerignore
Keeping the Dockerfile in the image allows the manifest creation script report the UBI image.
> Remove Dockerfile from .dockerignore file

- app/controllers/api/v1x2/stageaction/_modal.html.erb
- app/controllers/api/v1x2/stageaction/show.html.erb
This PR moves the comment field into a modal, accessed by pressing  "Approve", "Deny", or "Comment" - the same behavior used in the Approval UI.
Jira: https://projects.engineering.redhat.com/browse/SSP-1780
> Add comment modal

- spec/open_api_spec.rb
I've adjusted the spec that uses the random path prefix creator since it pulls from the dictionary of words in /usr/share/dict/words, and apparently on Travis that dictionary contains words with accents/strange characters. So now we just simply ensure that the resulting request url is encoded as it should be.
I've also added a spec explicitly to show that we handle encodings, even though it's basically identical to the spec above it.
This should fix issues like this one https://travis-ci.org/github/RedHatInsights/approval-api/jobs/722758928
> Fix Travis issue with strange encodings in a URL

- app/models/workflow.rb
- spec/models/workflow_spec.rb
https://projects.engineering.redhat.com/browse/SSP-1745
When the two sequence columns are out of sync by whatever reason QA is having difficulty to perform tests. This provides a mechanism to bring them back to synchronization.
Temporary. To be removed after sequence is retired
> Force to resync internal_sequence with sequence through seeding

- app/services/mixins/group_validate_mixin.rb
- spec/services/request_update_service_spec.rb
RBAC error during runtime will cause approval request pending forever. This PR rescues such errors and updates request with failed state.
https://projects.engineering.redhat.com/browse/SSP-1814
> Fails request if RBAC error raises during runtime

- app/models/workflow.rb
- app/services/workflow_update_service.rb
- db/migrate/20200921142042_remove_sequence_from_workflows.rb
- db/schema.rb
- public/doc/openapi-3-v1.2.json
- spec/controllers/v1.2/workflows_controller_spec.rb
- spec/models/workflow_spec.rb
Sequence has been replaced by internal_sequence, and UI has switched to use internal_sequence. Now it is time to officially remove sequence from workflows.
The original thought was to introduce a new API version. Our current API version is v0.1.2. Since we have made database change, it is impossible to support both v0.1.2 and v0.1.3. And if we simply replace v0.1.2 by v0.1.3, it is impossible to make all other services such as catalog-api and UI to update their client version simultaneously. The best option is to keep the existing version.
https://issues.redhat.com/browse/SSP-1843
> Remove sequence from workflows

- app/controllers/api/v1x2/workflows_controller.rb
- public/doc/openapi-3-v1.2.json
- spec/controllers/v1.2/workflows_controller_spec.rb
https://issues.redhat.com/browse/SSP-1856
https://issues.redhat.com/browse/SSP-1857
Fix openapi spec for workflow reposition/link/unlink. All of them should return 204.
Raise 400 error if no param is given in the body of reposition api.
> Fix reposition api return code and required params

- .codeclimate.yml
- .rubocop.yml
Just mimicking what we did in catalog-api so that any future PRs for approval-api get updated with the "right" style guide. I imagine this may eventually change to use the RedHatInsights one that Jacob is putting together: https://github.com/RedHatInsights/insights-api-common-rails/pull/210
> Update codeclimate and rubocop yml to use manageiq-style

- Dockerfile
The old Dockerfile deletes .so files. Bundle install fetches and installs latest nokogiri 1.11.1. When the pod starts it fails immediately with `LoadError: cannot load such file -- nokogiri/nokogiri"`. 
I have tested that the pod starts properly if we leave those files un-removed.
@lindgrenj6 Not sure why the Dockerfile worked until now. I feel it is safe to leave the library files un-removed. Please review.
> Not to delete so files

- .codeclimate.yml
- .rubocop.yml
- .yamllint
We're using this in catalog-api but approval-api was still using the old manageiq-style reference. Just updating this to be more in line with RedHat insights.
The codeclimate test in this likely won't pass because it needs to be merged before codeclimate actually picks up the changes. Also included the `.yamllint` file so that dippy-bot doesn't complain.
> Reference RedHatInsights/insights-api-common-rails for rubocop and codeclimate yamls

- app/services/jbpm_process_service.rb
- app/services/request_update_service.rb
- spec/services/jbpm_process_service_spec.rb
- spec/services/request_update_service_spec.rb
This addresses two issues
1. Upon each request finishing we need to send a signal to PAM telling it the process finished. If the signal fails it should not affect our approval request state. We can thus safely ignore the error instead of turning the request's state to failed.
2. `RequestUpdateService#finish_request` skips sending the signal if `request_finished` is true. However this method in the context always returns true so that signal is never triggered. Removing this check will force the signal to be sent. Even if it fails it has no impact to the request itself due to the change in 1.
> Do not raise error if signal fails

- app/services/request_update_service.rb
- spec/services/request_update_service_spec.rb
https://issues.redhat.com/browse/SSP-1779
The problem with group_finished event was the decision is always `undecided`. The event was sent before the request was saved. Now move the sending after the request has been updated.
Also fixed the issue that request_started event were sent multiple times when multiple groups were involved.
> Send group_finished event after update

- app/services/action_create_service.rb
- spec/services/action_create_service_spec.rb
https://issues.redhat.com/browse/SSP-2060
Should raise an error if the comment is blank (including empty string or nil) when operation is deny or memo.
> Raise an error if comment is empty

- pr_check.sh
We are switching to use absolute dir paths to avoid confusion
Also, I incorporated your quay `LABEL` approach into the common `build.sh`: https://github.com/RedHatInsights/bonfire/blob/master/cicd/build.sh#L32
> Updates to PR check

- .dockerignore
The main purpose is to trigger a build and deploy to cloud
> simplify .dockerignore

- config/application.rb
- config/initializers/controller_test.rb
We are seeing occasionally the controllers fail to serve endpoints.
Try to load rest controllers at startup for debugging.
> Change the autoload_paths to sync with other apps
