Gemfile

rails to 5.1
pg to 1.0
remove comments auto generated by swagger

update gem versions

---

db/seeds.rb

Use seeding method to create a default template called `Basic`. The `ext_ref` attribute is subject to future update. We may allow the BPM to update this attribute during its startup procedure.

Seed default template

---

docker-assets/entrypoint

Add an entrypoint script

---

Gemfile

Upgrade Rails minimum patch version for CVE-2018-16476

---

config/initializers/callback_terminator.rb

Ditto https://github.com/ManageIQ/service_portal-api/pull/67

Remove deprecated callback_terminator

---

app/controllers/api/v0/admins_controller.rb
app/controllers/concerns/exception_handler.rb
app/controllers/mixins/user_operations_mixin.rb
app/services/workflow_create_service.rb
public/doc/swagger-2.yaml
spec/requests/workflows_spec.rb
spec/services/workflow_create_service_spec.rb

Change the POST action of workflow. The input parameters contain an array of approval group ids.

Change endpoint to create workflow with groups

---

public/doc/swagger-2.yaml

Refactor swagger yaml file to have more clear parameters definitions for endpoints.

Refactor swagger yaml to have more clear in/out parameters

---

config/initializers/action_dispatch-routing-option_redirect.rb
config/routes.rb
spec/requests/groups_spec.rb

Support major version forwarding.
Reference: https://github.com/ManageIQ/service_portal-api/pull/109

Support major version forwarding

---

.gitignore
public/approval/v0.0.1/openapi.json

Fixed  type and format for notified_at

Fixed  type and format for notified_at

---

public/approval/v0.0.1/openapi.json
public/approval/v0.1.0/openapi.json

Fix `allOf` inheritance relationship in openapi json file

Fix openapi.json to set allOf correctly

---

Dockerfile
docker-assets/entrypoint

Creating the database requires additional credentials and it will
be created for us in both the RDS and container case

Use the postgres 10 packages and don't create the database

---

config/application.rb
config/environments/production.rb

Same problem as https://github.com/ManageIQ/catalog-api/pull/106

Don't eager load code on boot

---

Gemfile

Update activerecord to 5.2.2.1

Update activerecord to 5.2.2.1 for CVE

---

app/services/request_create_service.rb
app/services/stage_update_service.rb
db/migrate/20190329151023_add_random_access_key_to_stages.rb
db/schema.rb
spec/services/request_create_service_spec.rb

It is used by external limit access without login. It gets cleared once the stage is in finished state.

Add a random id column to stages table

---

public/approval/v1.0/openapi.json

Removed api_auth_key

---

app/models/request.rb
spec/models/request_spec.rb

https://github.com/ManageIQ/approval-api/issues/76

Allow no requester is set in request creation

---

app/controllers/api/v1x0/requests_controller.rb
spec/requests/v1.0/requests_spec.rb

Fixes #79 
https://github.com/rails/rails/commit/e86524c0c5a26ceec92895c830d1355ae47a7034

StrongParameters with hash values have to be at the end

---

app/models/template.rb
spec/models/template_spec.rb

The type is required to find the corresponding service class.

Add missing processor_type

---

app/controllers/api/v1x0/workflows_controller.rb

https://projects.engineering.redhat.com/browse/SSP-280

Fixed return code to 404

---

public/approval/v1.0/openapi.json

https://projects.engineering.redhat.com/browse/SSP-260

Changed id type to string

---

app/services/jbpm_process_service.rb

Get all process_options under the scope of org_admin

---

app/models/action.rb
app/services/action_create_service.rb
app/services/request_create_service.rb
app/services/stage_update_service.rb
spec/models/action_spec.rb
spec/requests/v1.0/workflows_spec.rb
spec/services/action_create_service_spec.rb
spec/services/request_create_service_spec.rb
spec/services/stage_update_service_spec.rb

Auto filled attributes of requester and processed_by if they are not set.

Enabled to auto fill requester and processed_by attributes

---

public/approval/v1.0/openapi.json

https://projects.engineering.redhat.com/browse/SSP-332
The openapi generator was having issues with the allOf calls. Spoke with Bill and the best path forward was to just remove them since they aren't really adding anything.

Fix OpenAPI Generator by removing all 'allOf' calls

---

app/controllers/api/v1x0/requests_controller.rb
public/approval/v1.0/openapi.json
spec/controllers/v1.0/requests_controller_spec.rb

https://projects.engineering.redhat.com/browse/SSP-315

Add filters validation

---

app/services/action_create_service.rb

https://projects.engineering.redhat.com/browse/SSP-485

Fixed typo error in raising exceptions

---

public/approval/v1.0/openapi.json

https://projects.engineering.redhat.com/browse/SSP-431

Corrected default limit value to 100

---

Jenkinsfile-smoke.groovy

Add Jenkinsfile-smoke.groovy to be used for smoke test phase

Add Jenkinsfile-smoke.groovy to be used for smoke test phase

---

app/controllers/api/v1x0/actions_controller.rb
app/controllers/api/v1x0/requests_controller.rb
app/models/request.rb
app/services/stage_update_service.rb
config/routes.rb
public/approval/v1.0/openapi.json
spec/controllers/v1.0/actions_controller_spec.rb
spec/models/request_spec.rb

Add an endpoint to cancel the request: requests/:id/cancel
This PR is related with: https://github.com/ManageIQ/approval-api/pull/127

Added requests/:id/actions endpoint

---

Jenkinsfile-smoke.groovy

Some fixes for path and remove white space

Some name fixes for Jenkinsfile-smoke.groovy

---

public/doc/openapi-3-v1.0.0.json

https://projects.engineering.redhat.com/browse/SSP-522

Added limit/offset to CollectionMetadata in openapi spec

---

app/controllers/api/v1x0/graphql_controller.rb
config/routes.rb
public/doc/openapi-3-v1.0.0.json
spec/controllers/v1.0/graphql_controller_spec.rb

https://projects.engineering.redhat.com/browse/SSP-543
depends on https://github.com/ManageIQ/manageiq-api-common/pull/86

Add GraphQL support

---

lib/rbac/roles.rb

Updated local variable `@roles` when role is created or deleted.

Keep roles in sync after role creation/deletion

---

app/controllers/api/v1x0/workflows_controller.rb
app/services/access_process_service.rb
app/services/workflow_create_service.rb
app/services/workflow_update_service.rb
lib/rbac/policies.rb
lib/rbac/sync.rb
lib/tasks/sync_rbac_roles.rake
spec/controllers/v1.0/workflows_controller_spec.rb
spec/services/access_process_service_spec.rb
spec/services/workflow_create_service_spec.rb
spec/services/workflow_update_service_spec.rb

`rake approval:sync_rbac_roles` task is added to sync RBAC roles for workflows.

Added a rake task to sync RBAC roles for existing workflows

---

app/controllers/api/v1x0/actions_controller.rb
app/controllers/api/v1x0/mixins/index_mixin.rb
app/controllers/api/v1x0/requests_controller.rb
app/controllers/api/v1x0/stages_controller.rb
app/controllers/api/v1x0/templates_controller.rb
app/controllers/api/v1x0/workflows_controller.rb
app/controllers/concerns/exception_handler.rb
lib/exceptions.rb
lib/rbac/access.rb
spec/controllers/v1.0/requests_controller_spec.rb
spec/controllers/v1.0/stages_controller_spec.rb
spec/controllers/v1.0/templates_controller_spec.rb
spec/controllers/v1.0/workflows_controller_spec.rb

This is the fifth PR to enable RBAC support in Approval service: added RBAC checking on resource index action.

Added rbac to resource index action

---

app/controllers/api/v1x0/workflows_controller.rb
app/services/workflow_update_service.rb
config/routes.rb
spec/controllers/v1.0/requests_controller_spec.rb
spec/controllers/v1.0/workflows_controller_spec.rb
spec/services/access_process_service_spec.rb
spec/services/workflow_create_service_spec.rb
spec/services/workflow_update_service_spec.rb

Added back missing commit files.

Restored RBAC files

---

app/controllers/api/v1x0/actions_controller.rb
app/controllers/concerns/exception_handler.rb
spec/controllers/v1.0/actions_controller_spec.rb

https://projects.engineering.redhat.com/browse/SSP-537

Return code 422 for invalid state transition

---

public/doc/openapi-3-v1.0.0.json

Updated openapi.json with three new introduced endpoints:
`admin/requests`
`approver/requests`
`requester/requests`
https://projects.engineering.redhat.com/browse/SSP-688

Added new endpoints into openapi.json

---

app/controllers/api/v1/graphql_controller.rb
app/controllers/api/v1x0/graphql_controller.rb
public/doc/openapi-3-v1.0.0.json

Similar to https://github.com/ManageIQ/catalog-api/pull/401
@abellotti, @mkanoor please review.

Perferring to version the Graphql controller

---

app/controllers/application_controller.rb
spec/controllers/v1.0/workflows_controller_spec.rb
spec/support/request_spec_helper.rb

Depends on ManageIQ/manageiq-api-common#115

Entitlement check switched to Ansible

---

Gemfile

Switch to manageiq-api-common v1.0.2

---

app/controllers/api/v1x0/requests_controller.rb
spec/controllers/v1.0/requests_controller_spec.rb

A follow-up PR to address remaining issue in #178

Use constant defined in manageiq-api-common

---

app/controllers/api/v1x0/stageaction_controller.rb
app/controllers/concerns/exception_handler.rb

https://projects.engineering.redhat.com/browse/SSP-502
It was originally fixed in commit 361c9e2 but got accidentally reverted. Refix.

Corrected 500 error code to bad_request 400

---

app/controllers/api/v1x0/actions_controller.rb

https://projects.engineering.redhat.com/browse/SSP-813

Only restrict regular user to create approve/deny actions

---

app/services/add_remote_tags.rb
app/services/get_remote_tags.rb
app/services/remote_tagging_service.rb
app/services/workflow_find_service.rb
app/services/workflow_link_service.rb
spec/controllers/v1.0/workflows_controller_spec.rb
spec/services/add_remote_tags_spec.rb
spec/services/get_remote_tags_spec.rb
spec/services/workflow_find_service_spec.rb
spec/services/workflow_link_service_spec.rb

- Fetches tags from remote services
- Finds workflows that match the tag name

Added support for finding workflows based on remote tags

---

app/controllers/api/v1x0/mixins/index_mixin.rb
public/doc/openapi-3-v1.0.0.json
spec/controllers/v1.0/actions_controller_spec.rb
spec/controllers/v1.0/stages_controller_spec.rb
spec/controllers/v1.0/workflows_controller_spec.rb

1. All `stage` related definitions are removed;
2. Combined `In` and `Out` schema definitions into one;

Cleaned up openapi spec file

---

app/services/workflow_find_service.rb
spec/factories/tag_links.rb
spec/services/request_create_service_spec.rb
spec/services/workflow_find_service_spec.rb
spec/support/tag_resources_shared_context.rb

Catalog would be sending a collection of TagResources and this
code will return a list of workflows sorted by the sequence number

Fetch sorted workflows based on TagResources

---

app/services/request_create_service.rb
app/services/request_update_service.rb
app/services/workflow_find_service.rb
spec/services/request_create_service_spec.rb

Reenable and fix request_create_service spec
Fix bugs found through spec tests.

Reenable and fix request_create_service spec

---

app/controllers/api/v1/actions_controller.rb
app/controllers/api/v1/mixins/rbac_mixin.rb
app/models/concerns/approval_permissions.rb
spec/controllers/v1.0/actions_controller_spec.rb
spec/controllers/v1.0/graphql_controller_spec.rb
spec/controllers/v1.0/requests_controller_spec.rb
spec/factories/actions.rb

In this PR:
1. Changed controllers and RBAC to remove `stage`;
2. Enabled spec tests;

Changed Controller/rbac for tag based service

---

app/services/request_update_service.rb

https://projects.engineering.redhat.com/browse/SSP-1000

Fix bypassing jbpm logic

---

app/services/request_update_service.rb

This is temporary until BPM is fixed

Auto notify if bypass jbpm

---

app/controllers/api/v1/requests_controller.rb
config/routes.rb
public/doc/openapi-3-v1.0.0.json
spec/controllers/v1.0/requests_controller_spec.rb
spec/factories/requests.rb

The return body will be an object (Hash).
Also expose `created_at` in `Request` schema.

Add endpoint /requests/:id/content

---

public/doc/openapi-3-v1.0.0.json

+ some minor fix in the openapi spec
Fixes Jira https://projects.engineering.redhat.com/browse/SSP-1044

Add start as an action operation enum value.

---

app/services/add_remote_tags.rb
app/services/delete_remote_tags.rb
app/services/get_remote_tags.rb
app/services/mixins/tag_mixin.rb
app/services/remote_tagging_service.rb
app/services/workflow_find_service.rb
app/services/workflow_link_service.rb
app/services/workflow_unlink_service.rb
public/doc/openapi-3-v1.0.0.json
spec/controllers/v1.0/requests_controller_spec.rb
spec/controllers/v1.0/workflows_controller_spec.rb
spec/services/add_remote_tags_spec.rb
spec/services/delete_remote_tags_spec.rb
spec/services/get_remote_tags_spec.rb
spec/services/request_create_service_spec.rb
spec/services/workflow_find_service_spec.rb
spec/services/workflow_link_service_spec.rb
spec/support/tag_resources_shared_context.rb

Uses the latest tagging changes 
* tag end point to create and assign new tags
* untag end point to delete tags
Waiting on some of the other PRs to get merged first
https://github.com/RedHatInsights/catalog-api/pull/495

Support for new tagging changes

---

app/controllers/api/v1/actions_controller.rb
app/controllers/api/v1/mixins/rbac_mixin.rb
app/controllers/api/v1/requests_controller.rb

Reduced log messages to improve performance.

Suppressed log messages

---

app/controllers/api/v1/stageaction_controller.rb
app/services/jbpm_process_service.rb
app/services/request_update_service.rb
spec/controllers/v1.0/requests_controller_spec.rb
spec/services/jbpm_process_service_spec.rb

This PR depends on https://github.com/RedHatInsights/approval-process/pull/22

Enabled bpm service for tag based approval

---

spec/models/template_spec.rb

Use with_modified_env block to set environment variables for seeding test

---

Gemfile

Same updates as https://github.com/RedHatInsights/catalog-api/pull/538

Gem updates based on Hakiri scan

---

README.md

Hakiri webhook updated after repo moved to RedHatInsights org.

Update README.md badge URLs

---

app/services/request_create_service.rb
spec/services/request_create_service_spec.rb

Fixes an issue when the code is still running inside the transaction block, the newly created approval requests are not accessible from another http request.
Move the starting logic outside the transaction block and run it in another thread. Our debugging discovered that the starting logic can take quite a few seconds. Running in a background thread can help to return the call sooner.

Move start request logic to a new thread

---

app/services/event_service.rb

- x-rh-identity
- x-rh-insights-request-id
Are added to the Kafka Message header to be consistent with topolology
and sources API
https://github.com/RedHatInsights/topological_inventory-api/pull/270

Add headers to Kafka Messages

---

spec/controllers/v1.0/requests_controller_spec.rb

Re-enable two spec tests.
Refactor some existing tests.

Refactor RequestsController spec tests

---

Dockerfile

https://projects.engineering.redhat.com/browse/SSP-1149
Update Dockerfile to use a RHEL based image rather than `manageiq/ruby` which was based on CentOS. This is for our security audit in the future. 
Tested this in my own namespace with my own database and had great success:
cc @gmcculloug @carbonin @gtanzillo exhibit A of converting our services to use UBI and thus RHEL based images.

Update Dockerfile to use UBI instead of CentOS

---

Gemfile
config/environments/production.rb

Remove css compression

---

app/controllers/api/v1/stageaction/_request.html.erb
app/controllers/api/v1/stageaction/result.html.erb

Follow-up to: https://github.com/RedHatInsights/approval-api/pull/277 addressing case changes mentioned by @sbuenafe-rh  
Date/Time comments still need to be addressed. @bzwei Can you help with those?

Title Adjustments

---

app/controllers/application_controller.rb

Based on https://github.com/RedHatInsights/catalog-api/pull/608

Add logging to start and end of a request

---

Gemfile
app/controllers/application_controller.rb
app/services/context_service.rb

Changed to use tenant from request, similar work as following PR:
https://github.com/RedHatInsights/catalog-api/pull/603

Changed to handle tenant from request

---

Gemfile
config/initializers/custom_exception_mappings.rb

Changed to returned `service_unavailable` whenever RBAC has network issues

Change error code to 503 when RBAC has network errors

---

Gemfile

Resolves [CVE-2020-5247](https://hakiri.io/github/RedHatInsights/catalog-api/master/21251fb1df3d6b5fc045cc413db851b515276fca/warnings?name=Cross-Site+Scripting)

Fix hakiri security warning for Puma

---

.gitignore
.sonar/sonar-scanner.properties.template
Gemfile
lib/tasks/sonarqube_scan.rake

Pretty self explanatory. Similar to RedHatInsights/catalog-api#615
Link to results: https://sonarqube.corp.redhat.com/dashboard?id=InsightsPlatform%3Ajlindgren-approval-api

Add Sonarqube rake task and appropriate files

---

app/services/request_create_service.rb
spec/services/request_create_service_spec.rb

https://projects.engineering.redhat.com/browse/SSP-1381

Change comments to Auto-approved

---

app/controllers/api/v1x2.rb
app/controllers/api/v1x2/workflows_controller.rb
app/services/mixins/group_validate_mixin.rb
app/services/workflow_create_service.rb
app/services/workflow_get_service.rb
app/services/workflow_link_service.rb
app/services/workflow_update_service.rb
config/routes.rb
config/routes/v1x2.rb
db/migrate/20200320110205_change_group_refs_format.rb
db/schema.rb
public/doc/openapi-3-v1.2.json
spec/controllers/v1.0/requests_controller_spec.rb
spec/controllers/v1.0/workflows_controller_spec.rb
spec/controllers/v1/root_controller_spec.rb
spec/services/request_create_service_spec.rb
spec/services/workflow_create_service_spec.rb
spec/services/workflow_find_service_spec.rb
spec/services/workflow_get_service_spec.rb
spec/services/workflow_link_service_spec.rb
spec/services/workflow_update_service_spec.rb
spec/spec_helper.rb
spec/support/request_spec_helper.rb
spec/support/v1x2_helper.rb

https://projects.engineering.redhat.com/browse/SSP-1354
Format of group_refs changed in workflow API, therefore made a new version v1.2.

Store name together with uuid for group_refs in workflows

---

public/doc/openapi-3-v1.2.json

https://projects.engineering.redhat.com/browse/SSP-707

Change error response to conform to IPP

---

Gemfile

Stable branch PR of https://github.com/RedHatInsights/approval-api/pull/323

[Stable] Lock api-common to 3.9

---

Gemfile
spec/controllers/v1.0/actions_controller_spec.rb
spec/controllers/v1.0/graphql_controller_spec.rb
spec/controllers/v1.0/requests_controller_spec.rb
spec/controllers/v1.0/templates_controller_spec.rb
spec/controllers/v1.0/workflows_controller_spec.rb
spec/support/rbac_shared_contexts.rb

Updated insights-api-common to version 3.10 and fixed all spec failures

Updated api-common version to 3.10

---

public/doc/openapi-3-v1.2.json
spec/controllers/v1.0/workflows_controller_spec.rb

https://projects.engineering.redhat.com/browse/SSP-1431
Similar work as https://github.com/RedHatInsights/catalog-api/pull/605

Set format of group_ref to be uuid

---

Gemfile
app/controllers/api/v1x0/graphql_controller.rb

Related to PR RedHatInsights/insights-api-common-rails#177

Added graphql args in resolver

---

Gemfile

When debugging in prod environment the byebug allows us to step
thru the code.
(1) Create a simple script with embedded byebug statements
(2) run the script using bin/rails r
(3) Step into the code that could be causing the problem
Sample Script that we recently used in catalog
```
require 'byebug'
order_number = 283
o = Order.find(order_number).order_items.first
req = {:headers => o.context['headers'],
:original_url => o.context['original_url']}
byebug
Insights::API::Common::Request.current = req
Thread.current[:user_context] = UserContext.new(Insights::API::Common::Request.current, {})
access = Thread.current[:user_context].access
scopes = access.scopes('portfolios','order', 'catalog')
ActsAsTenant.with_tenant(Tenant.find_by(:external_tenant => …
```

Added byebug

---

app/models/concerns/metadata.rb
spec/models/request_spec.rb
spec/models/template_spec.rb
spec/models/workflow_spec.rb

Same as https://github.com/RedHatInsights/catalog-api/pull/690

Used class method to cache PolicyClass name

---

app/controllers/api/v1x0/graphql_controller.rb

This is a workaround of the issue of graphql not able to evaluate the lambda correctly.

Temporarily fix graphql lambda issue

---

app/controllers/api/v1x0/graphql_controller.rb

This PR is to replace the previous temporarily fix: 
https://github.com/RedHatInsights/approval-api/pull/334

Use graphql context to fix controller cached issue

---

app/controllers/application_controller.rb
app/policies/user_context.rb
spec/policies/user_context_spec.rb

Similar work as https://github.com/RedHatInsights/catalog-api/pull/719

Added missing yield in user_context

---

config/application.rb
config/environments/production.rb

The environment variable is called RAILS_LOG_LEVEL with the valid values
- info
- debug
- error
- warn

Get log level from environment

---

public/doc/openapi-3-v1.2.json

https://projects.engineering.redhat.com/browse/SSP-1259
Also reword throughout the document to make them conform into similar style.

Add title, description, and examples to attributes

---

Gemfile
app/models/workflow.rb
app/services/workflow_create_service.rb
app/services/workflow_update_service.rb
db/migrate/20200430123949_add_unique_index_to_sequence.rb
db/schema.rb
spec/models/workflow_spec.rb

Remove dependency on acts_as_list. Implement a simple logic for sequence.
https://projects.engineering.redhat.com/browse/SSP-1471

Make sequence unique

---

spec/models/workflow_spec.rb

This reverts commit a58c8f83769af4575773d48a88eb6e7b7b6731ac, reversing
changes made to 5ff0892d629f4402a05e40a21b98b4e59c471d35.

Revert "Merge branch 'stable' into master"

---

app/controllers/api/v1x2/stageaction/result.html.erb
app/controllers/api/v1x2/stageaction/show.html.erb

jira: https://projects.engineering.redhat.com/browse/SSP-1561

Update title on unauthenticated approval screens

---

Gemfile

Bump Puma to 3.12.6

---

app/services/event_service.rb
app/services/workflow_delete_service.rb
spec/services/event_service_spec.rb

This is a follow-up PR to address comments in #381

EventService takes default value in initilize method

---

.travis.yml

Mistakingly left my branch name in the download URL

Update openapi-validator.sh URL

---

app/controllers/api/v1x2/stageaction/_header.html.erb
app/controllers/api/v1x2/stageaction/_request.html.erb
app/controllers/api/v1x2/stageaction/result.html.erb
app/controllers/api/v1x2/stageaction/show.html.erb
app/controllers/api/v1x2/stageaction_controller.rb

Jira: https://projects.engineering.redhat.com/browse/SSP-1675
Old
New
Old
New

Approval screen styling updates

---

app/controllers/api/v1x2/stageaction/show.html.erb

Jira: https://projects.engineering.redhat.com/browse/SSP-1699

Add introductory text

---

app/controllers/api/v1x2/stageaction/result.html.erb
app/controllers/api/v1x2/stageaction_controller.rb

Follow-up to: https://github.com/RedHatInsights/approval-api/pull/391
Jira: https://projects.engineering.redhat.com/browse/SSP-1780

Add "undecided" status for comments

---

app/controllers/api/v1x2/stageaction/_header.html.erb
app/controllers/api/v1x2/stageaction/_toast.html.erb
app/controllers/api/v1x2/stageaction/result.html.erb

This PR replaces the Inline alerts with Toast alerts
Jira: https://projects.engineering.redhat.com/browse/SSP-1780

Add toast notification

---

app/controllers/api/v1x2/stageaction/_modal.html.erb

Jira: https://projects.engineering.redhat.com/browse/SSP-1801
Old (Approve)
New (Approve)
Old (Deny)
New (Deny)
Old (Comment)
New (Comment)

Styling updates to the three modals

---

app/services/event_service.rb
app/services/request_create_service.rb

https://issues.redhat.com/browse/SSP-1815
I feel no spec test is needed for this enhancement since no logic change is made.

Log the request instance and event payload

---

spec/open_api_spec.rb

due to the change by https://github.com/RedHatInsights/insights-api-common-rails/pull/173

Fix spec due to api-common no longer allows redirect POST and PATCH

---

Dockerfile

Sprint 68 merge master to stable fix pod issues

---

.dockerignore
Dockerfile
Gemfile
config/initializers/clowder_config.rb
deploy/clowdapp.yaml
docker-assets/entrypoint
docker-assets/run_rails_server
pr_check.sh

https://issues.redhat.com/browse/SSP-2155

Clowder Support

---

deploy/clowdapp.yaml

The purpose it to avoid conflict in stage with existing approval-api service

Append v2 to deployment name

---

Dockerfile

Align with https://github.com/RedHatInsights/catalog-api/blob/main/Dockerfile#L15
Hopefully it can reduce the number of dependent packages in the image.

Use dnf command to do cleaning

---

Dockerfile

https://issues.redhat.com/browse/SSP-2502

Upgrade base ubi to 8.4

---

Dockerfile

https://issues.redhat.com/browse/SSP-2502

bump the base image to 8.5
